name: gaia
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  flutter_reactive_ble: any
  sqflite: any
  path: any
  shared_preferences: any
  cupertino_icons: ^1.0.2
  maybe: ^0.4.0
  flex_color_scheme: ^5.1.0
  provider: any
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.4
  intl_phone_number_input: ^0.7.1
  cloud_firestore: ^4.1.0
  cloud_firestore_odm: ^1.0.0-dev.42
  json_annotation: ^4.7.0
  blufi_plugin: ^1.0.4
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  cloud_firestore_odm_generator: ^1.0.0-dev.42
  json_serializable: ^6.5.4
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
  - 'assets/images/'
  - 'assets/images/2x/'
  - 'assets/images/4x/'
  - 'assets/images/tamagochi/Faces/'
  - 'assets/images/tamagochi/Faces/2x/'
  - 'assets/images/tamagochi/Faces/4x/'
  - 'assets/images/tamagochi/Accessories/'
  - 'assets/images/tamagochi/Accessories/2x/'
  - 'assets/images/tamagochi/Accessories/4x/'
  - 'assets/images/tamagochi/Plants/'
  - 'assets/images/tamagochi/Plants/2x/'
  - 'assets/images/tamagochi/Plants/4x/'
  - 'assets/images/tamagochi/Pots/'
  - 'assets/images/tamagochi/Pots/2x/'
  - 'assets/images/tamagochi/Pots/4x/'
  - 'assets/images/tamagochi/Icons/'
  - 'assets/images/tamagochi/Icons/2x/'
  - 'assets/images/tamagochi/Icons/4x/'
  fonts:
  - family: Roboto
    fonts:
      - asset: assets/fonts/Roboto/Roboto-Thin.ttf
        weight: 100
      - asset: assets/fonts/Roboto/Roboto-BlackItalic.ttf
        weight: 100
        style: italic
      - asset: assets/fonts/Roboto/Roboto-Light.ttf
        weight: 300
      - asset: assets/fonts/Roboto/Roboto-LightItalic.ttf
        weight: 300
        style: italic
      - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        weight: 400
      - asset: assets/fonts/Roboto/Roboto-Italic.ttf
        weight: 400
        style: italic
      - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        weight: 500
      - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        weight: 700
      - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: assets/fonts/Roboto/Roboto-Black.ttf
        weight: 900
      - asset: assets/fonts/Roboto/Roboto-BlackItalic.ttf
        weight: 900
        style: italic
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins/Poppins-Thin.ttf
        weight: 100
      - asset: assets/fonts/Poppins/Poppins-BlackItalic.ttf
        weight: 100
        style: italic
      - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf
        weight: 200
        style: italic
      - asset: assets/fonts/Poppins/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
        weight: 300
        style: italic
      - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins/Poppins-Italic.ttf
        weight: 400
        style: italic
      - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        weight: 700
      - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
        weight: 800
        style: italic
      - asset: assets/fonts/Poppins/Poppins-Black.ttf
        weight: 900
      - asset: assets/fonts/Poppins/Poppins-BlackItalic.ttf
        weight: 900
        style: italic
